### ISSUE TITLE
使用dva+react router4搭建的嵌套路由,浏览器不显示

### ISSUE THREAD

**Issue by jack-hate-titanic** [dkvirus/dva#9]
如题，直接上代码了，这是router.js文件
```
import React from 'react';
import Meeting from "./routes/Meeting/Meeting";
import {
  BrowserRouter as Router,
  Route,
  Link,
  Switch,
} from 'react-router-dom'
function RouterConfig({ history }) {
  const Child=()=>{
    return <div>
      <h3>子组件</h3>
    </div>
  }
  return (
    <Router history={history}>
      <div>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/meeting">meeting</Link></li>
          <li><Link to="/bjfccp/tianxia">tianxia</Link></li>
        </ul>

        <hr/>
        <Switch>
          <Route  path="/" exact component={Meeting}/>
          <Route  path="/meeting" component={Meeting}/>
          <Route  path="/bjfccp/tianxia" component={Child}/>
        </Switch>
      </div>
    </Router>
  );
}

export default RouterConfig;

```

点击导航也能跳转到/bjfccp/tianxia页面，但是如果浏览器直接访问就不行

浏览器报的错误是
![qq 20180620180451](https://user-images.githubusercontent.com/17841561/41651996-8c73e3ae-74b4-11e8-8897-3638a7e9abc2.png)

打开index.js:1进去报的错误是
![81d 15le7eopye h7coyu](https://user-images.githubusercontent.com/17841561/41652173-f13517e0-74b4-11e8-8b5b-70eb64bf1c8f.png)

**Comment by dkvirus** [comment]
@Y-wson 我在本地也用 dva-cli 重新生成了一个脚手架，测试嵌套路由无论是点击跳转还是直接在浏览器跳转都是没问题的。请检查下你的版本是否太老旧。

```
dva-cli    v0.9.2
dva     v2.3.0
roadhog    v2.0.0
```

还有一个咱两代码区别地方在于我的 Router、Link 标签都是从 dva/route 库里引的。看你的代码 `BrowserRouter as Router` 而我的是直接用 Router 标签的。下面是我的代码。

```
import React from 'react';
import { Router, Route, Switch, Link } from 'dva/router';
import IndexPage from './routes/IndexPage';

function RouterConfig({ history }) {
  const Child=()=>{
    return <div>
      <h3>子组件</h3>
    </div>
  }

  return (
    <Router history={history}>
      <div>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/user/hello">tianxia</Link></li>
        </ul>

        <hr/>
        <Switch>
          <Route path="/" exact component={IndexPage} />
          <Route path="/user/hello" component={Child} />
        </Switch>
      </div>
    </Router>
  );
}

export default RouterConfig;
```

**Comment by jack-hate-titanic** [comment]
@dkvirus 加个qq1002783067，我重新搭建了，依然是这个问题

**Comment by dkvirus** [comment]
这是 dva 的一个大坑。

用 HashHistory 的时候浏览器直接访问形如"/a/b" 嵌套路由时没问题的，别忘了 HashHistroy 前面的 # 号。

用 BorwserHistory 会一直报错 `Uncaught SyntaxError: Unexpected token <`，解决方法为：将 `public/index.html` 里的 `index.js` 换成 `/index.js`。

![image](https://user-images.githubusercontent.com/29170168/41702191-c8431a5a-7561-11e8-8152-79612f97e759.png)

[原issue地址](https://github.com/dvajs/dva/issues/1614)

**Comment by Mjian-chen** [comment]
真的好坑呀，搞了一晚上，加个斜杆就行了，这个是什么梗啊。

**Comment by kitiho** [comment]
我靠 搞了一上午 才发现要在index前面加/
